### ISSUE TITLE
BUG: Não vai para o login quando sem sessão e id

### ISSUE THREAD

**Issue by fabriziomachado** [vecarrilho/agenda_unesc#86]
https://agendaprova.unesc.net/agenda/12

Se perder a sessão e tiver um id, deve ir para tela de login. Hoje está apresentando a tela de erro

![image](https://user-images.githubusercontent.com/7240/165991335-0f2814d9-1ada-4a51-9d56-bb2f403af412.png)

**Comment by fabriziomachado** [comment]
@vecarrilho favor verificar

**Comment by vecarrilho** [comment]
Por algum motivo o erro só ocorre em produção

**Comment by vecarrilho** [comment]
Resolvido, criado condição quando session estiver vazia e redirecionada para tela de login
