### ISSUE TITLE
Notificação do agendamento

### ISSUE THREAD

**Issue by fabriziomachado** [vecarrilho/agenda_unesc#87]
2 - após o agendamento, o sistema encaminhar e-mail ao aluno com dia, horários e locais das avaliações agendas. Isso porque, nos dois últimos dias de prova regular o sistema de agendamento não apresentou mais os horários e locais das provas agendadas) 

- ver possibilidade de usar uma api whats

**Comment by vecarrilho** [comment]
Notificação por email funcionando, só trocar as credenciais no .env

**Comment by vecarrilho** [comment]
Credenciais alteradas
